
services:
  db_postgres:
    image: postgres:14
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: LostAndFoundDB
    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


