# Generated by Django 5.1.3 on 2024-12-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(db_column='tx_items')),
            ],
        ),
        migrations.AddField(
            model_name='founditem',
            name='category',
            field=models.ForeignKey(db_column='tx_category', null=True, on_delete=django.db.models.deletion.PROTECT, to='item.category'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='category',
            field=models.ForeignKey(db_column='tx_category', null=True, on_delete=django.db.models.deletion.PROTECT, to='item.category'),
        ),
    ]
