# Generated by Django 5.1.3 on 2024-12-07 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('name', models.CharField(db_column='category_name')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='founditem',
            name='Category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='item.category'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='Category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='item.category'),
        ),
    ]
