# Generated by Django 5.1.3 on 2024-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='media/items_pictures'),
        ),
    ]
