# Generated by Django 5.1.3 on 2024-12-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_category_founditem_category_lostitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='items',
            new_name='name',
        ),
        migrations.AddField(
            model_name='founditem',
            name='city',
            field=models.CharField(db_column='tx_city', default='brasil', max_length=100),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='city',
            field=models.CharField(db_column='tx_city', default='brasil', max_length=100),
        ),
    ]
