# Generated by Django 5.1.1 on 2024-10-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_category_founditem_category_lostitem_category'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
    ]
