# Generated by Django 5.1.3 on 2024-12-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_items_category_name_founditem_city_and_more'),
        ('item', '0004_unacent'),
    ]

    operations = [
    ]
