# Generated by Django 5.1.3 on 2024-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(db_column='username', max_length=20, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined', verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, db_column='last_login', verbose_name='last login')),
                ('is_admin', models.BooleanField(db_column='is_admin', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('hide_email', models.BooleanField(db_column='hide_email', default=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
    ]
