# Generated by Django 5.1.3 on 2024-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cellphone',
            field=models.IntegerField(db_column='cellphone', default=0),
        ),
    ]
